# Generated by Django 5.2 on 2025-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_notification_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('allow_late_checkin', models.BooleanField(default=False)),
                ('late_threshold', models.IntegerField(default=15)),
                ('send_notifications', models.BooleanField(default=True)),
                ('max_leaves', models.IntegerField(default=2)),
                ('leave_notice_days', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
